import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Banner from '@/Component/HomeComponent/Banner'
import HomeAbout from '@/Component/HomeComponent/HomeAbout'
import PlayGames from '@/Component/HomeComponent/PlayGames'
import OurGames from '@/Component/HomeComponent/OurGames'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner></Banner>
      <HomeAbout></HomeAbout>
      <PlayGames></PlayGames>
      <OurGames></OurGames>
    </>
  )
}
